import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = resolve(root, "packages/tokens/src/tokens.json");
const cssPath = resolve(root, "packages/tokens/src/index.css");

const contract = JSON.parse(await readFile(sourcePath, "utf8"));

function flatten(node, path = [], output = new Map()) {
  if (!node || typeof node !== "object") return output;
  if (Object.hasOwn(node, "$value")) {
    output.set(path.join("/"), node);
    return output;
  }
  for (const [key, value] of Object.entries(node)) {
    if (!key.startsWith("$")) flatten(value, [...path, key], output);
  }
  return output;
}

const tokens = flatten(contract);

function resolveValue(value, seen = new Set()) {
  if (typeof value !== "string") return value;
  const match = value.match(/^\{(.+)\}$/);
  if (!match) return value;
  const target = match[1];
  if (seen.has(target)) throw new Error(`Circular token alias: ${target}`);
  const token = tokens.get(target);
  if (!token) throw new Error(`Unknown token alias: ${target}`);
  return resolveValue(token.$value, new Set([...seen, target]));
}

function formatNumber(value) {
  return Number(value.toFixed(4)).toString();
}

function toCssValue(path, token) {
  const value = resolveValue(token.$value);
  switch (token.$type) {
    case "dimension": {
      if (typeof value !== "string") return String(value);
      if (value.endsWith("%")) return `${formatNumber(parseFloat(value) / 100)}em`;
      if (value.endsWith("px")) {
        const px = parseFloat(value);
        return px === 0 ? "0" : `${formatNumber(px / 16)}rem`;
      }
      return value;
    }
    case "fontFamily":
      return `"${value}"`;
    case "cubicBezier":
      return `cubic-bezier(${value.join(", ")})`;
    case "number":
    case "fontWeight":
    case "opacity":
    case "duration":
    case "color":
    case "shadow":
      return Array.isArray(value) ? value.join(", ") : String(value);
    default:
      throw new Error(`Unsupported token type for ${path}: ${token.$type}`);
  }
}

const lines = [
  "/* Generated by pnpm tokens:build. Edit tokens.json instead. */",
  ":root {",
];
for (const [path, token] of [...tokens.entries()].sort(([a], [b]) => a.localeCompare(b))) {
  lines.push(`  --ey-${path.replaceAll("/", "-")}: ${toCssValue(path, token)};`);
}
lines.push("}", "");

await writeFile(cssPath, lines.join("\n"));
console.log(`Generated ${tokens.size} CSS custom properties at ${cssPath}`);
